/* ============================================================================
 * web/src/lib/test/golden.ts — golden-master helper (MIGRATION.md D-012, S05)
 * ----------------------------------------------------------------------------
 * Ports (S07 sanitize-html/validators/calendar/escape, S08 money) must be
 * byte-identical to their legacy oracle. The oracle is captured ONCE as a
 * fixture of {input, expected} vectors under web/tests/fixtures/*.json —
 * generated by running the LEGACY module over the inputs — and the ported
 * module must reproduce every vector.
 *
 * Usage (inside a *.test.ts):
 *   import vectors from '../fixtures/escape.json';
 *   itGolden('escape', vectors, (input) => esc(input));
 * ========================================================================== */
import { expect, it } from 'vitest';

export type GoldenVector<I, O> = { input: I; expected: O; note?: string };

export function itGolden<I, O>(
  name: string,
  vectors: readonly GoldenVector<I, O>[],
  fn: (input: I) => O,
): void {
  if (vectors.length === 0) throw new Error(`golden "${name}": empty fixture`);
  vectors.forEach((v, i) => {
    it(`golden: ${name} [${i}]${v.note ? ` — ${v.note}` : ''}`, () => {
      expect(fn(v.input)).toEqual(v.expected);
    });
  });
}
