// Vitest stand-in for $env/static/public (real module is generated by
// svelte-kit sync from the build env; unit tests must not depend on it).
export const PUBLIC_SUPABASE_URL = 'http://stub.supabase.local';
export const PUBLIC_SUPABASE_ANON_KEY = 'stub-anon-key';
