// S07 golden parity for $lib/calendar (port of js/utils/calendar.js).
// Fixtures were generated by RUNNING THE LEGACY MODULE with the zero-arg Date
// constructor pinned to fixture.pinnedNow (buildICS stamps DTSTAMP from "now");
// this suite pins vitest's fake clock to the SAME instant so the ICS output is
// byte-identical. All event timestamps carry explicit UTC offsets (G-002) —
// the generator verified NY vs Tokyo runs produce identical fixtures.
import { afterAll, beforeAll, describe, vi } from 'vitest';
import { itGolden, type GoldenVector } from '$lib/test/golden';
import { buildGoogleCalUrl, buildICS, type CalendarEvent } from '$lib/calendar';
import fixtureJson from '../fixtures/calendar.json';

type Fixture = {
  pinnedNow: string;
  buildGoogleCalUrl: GoldenVector<CalendarEvent, string>[];
  buildICS: GoldenVector<CalendarEvent, string>[];
};

const fx = fixtureJson as unknown as Fixture;

describe('calendar golden (legacy js/utils/calendar.js)', () => {
  beforeAll(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date(fx.pinnedNow));
  });
  afterAll(() => {
    vi.useRealTimers();
  });

  itGolden('buildGoogleCalUrl', fx.buildGoogleCalUrl, (ev) => buildGoogleCalUrl(ev));
  itGolden('buildICS', fx.buildICS, (ev) => buildICS(ev));
});
