// S07 golden parity for $lib/escape (port of js/utils/escape.js).
// Fixtures were generated by RUNNING THE LEGACY MODULE (tools in the S07
// session notes) — never regenerate them from the port (D-012).
import { describe } from 'vitest';
import { itGolden, type GoldenVector } from '$lib/test/golden';
import { esc, html, raw, SafeHtml } from '$lib/escape';
import escVectorsJson from '../fixtures/escape.json';
import htmlVectorsJson from '../fixtures/escape-html-template.json';

// --- fixture value decoding (mirrored from the generator) -------------------
// esc inputs are JSON values; {$undefined:true} marks `undefined`.
// html`` inputs are specs: { parts: string[], values: Val[] } where
// Val = JSON value | {$undefined:true} | {$raw: string} | {$html: spec} | Val[]
type HtmlSpec = { parts: string[]; values: unknown[] };

function decodeValue(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(decodeValue);
  if (v && typeof v === 'object') {
    const o = v as Record<string, unknown>;
    if (o.$undefined === true) return undefined;
    if (typeof o.$raw === 'string') return raw(o.$raw);
    if (o.$html) return decodeHtml(o.$html as HtmlSpec);
    return v;
  }
  return v;
}

function decodeHtml(spec: HtmlSpec): SafeHtml {
  const parts = spec.parts as unknown as TemplateStringsArray;
  return html(parts, ...spec.values.map(decodeValue));
}

const escVectors = escVectorsJson as unknown as GoldenVector<unknown, string>[];
const htmlVectors = htmlVectorsJson as unknown as GoldenVector<HtmlSpec, string>[];

describe('escape golden (legacy js/utils/escape.js)', () => {
  itGolden('esc', escVectors, (input) => esc(decodeValue(input)));
  itGolden('html tagged template', htmlVectors, (spec) => String(decodeHtml(spec)));
});
