// Golden parity for S08 money.ts vs legacy js/utils/number.js `money` (D-003,
// D-012). Fixtures were generated by RUNNING the legacy module over the inputs
// (tools in the S08 session notes) — never hand-written, never from the port.
//
// Legacy money() takes DOLLARS; the ported formatUSD takes CENTS. The golden
// therefore runs the full cents path on the same dollars input:
//   legacy money(x)  ==  formatUSD(toCents(x))
import { describe } from 'vitest';
import { itGolden, type GoldenVector } from '$lib/test/golden';
import { formatUSD, toCents } from '$lib/money';
import usd from '../fixtures/money-usd.json';
import guards from '../fixtures/money-guards.json';

describe('money golden: formatUSD(toCents(x)) === legacy money(x)', () => {
  itGolden('money-usd', usd as GoldenVector<string | number, string>[], (input) =>
    formatUSD(toCents(input)),
  );
});

// Legacy rendered any non-numeric input as "$0.00" (`Number(n) || 0`). toCents
// now throws on those (documented policy), but the display-only formatUSD keeps
// the exact legacy guard — these vectors are scale-free (they coerce to 0/NaN),
// so legacy money(garbage) and formatUSD(garbage) must agree byte-for-byte.
describe('money golden: formatUSD keeps the legacy non-numeric guard', () => {
  itGolden('money-guards', guards as GoldenVector<unknown, string>[], (input) =>
    formatUSD(input as number),
  );
});
