/* ============================================================================
 * web/tests/golden/pdf.test.ts — S09 golden parity for the pure pdf builders
 * ----------------------------------------------------------------------------
 * Fixtures were generated by RUNNING THE LEGACY js/lib/pdf.js under node
 * (D-012; see scratch tools/capture-pdf-builders.mjs). Function-valued fields
 * (kpiBox layout callbacks, churchDocDef header/footer/background) are not
 * JSON-serializable, so both the capture and this test evaluate them through
 * the IDENTICAL probe: footer at (2, 5); background at page 1 on LETTER
 * portrait 612x792pt. Loaders/delivery are browser-only and are out of golden
 * scope (VERIFICATION.md: assert docdef structure, never pdfmake bytes).
 * ========================================================================== */
import { describe } from 'vitest';
import { itGolden, type GoldenVector } from '$lib/test/golden';
import {
  CHURCH,
  CHURCH_ADDRESS,
  CONTENT_W,
  churchDocDef,
  kpiBox,
  sectionHeading,
  th,
  type ChurchDocDef,
  type ChurchDocDefOpts,
} from '$lib/pdf';
import constVectors from '../fixtures/pdf-constants.json';
import shVectors from '../fixtures/pdf-section-heading.json';
import thVectors from '../fixtures/pdf-th.json';
import kpiVectors from '../fixtures/pdf-kpi-box.json';
import docVectors from '../fixtures/pdf-church-docdef.json';

// ── probes (MUST mirror tools/capture-pdf-builders.mjs byte-for-byte) ────────
interface KpiLayout {
  hLineWidth: (i: number) => number;
  vLineWidth: (i: number) => number;
  hLineColor: (i: number) => string;
  vLineColor: (i: number) => string;
  paddingLeft: () => number;
  paddingRight: () => number;
  paddingTop: () => number;
  paddingBottom: () => number;
}

function probeKpi(box: unknown) {
  const b = box as { table: unknown; layout: KpiLayout };
  const L = b.layout;
  return {
    table: b.table,
    layout: {
      hLineWidth: L.hLineWidth(0),
      vLineWidth0: L.vLineWidth(0),
      vLineWidth1: L.vLineWidth(1),
      hLineColor: L.hLineColor(0),
      vLineColor0: L.vLineColor(0),
      vLineColor1: L.vLineColor(1),
      paddingLeft: L.paddingLeft(),
      paddingRight: L.paddingRight(),
      paddingTop: L.paddingTop(),
      paddingBottom: L.paddingBottom(),
    },
  };
}

function probeDocDef(d: ChurchDocDef) {
  return {
    pageSize: d.pageSize,
    pageOrientation: d.pageOrientation,
    pageMargins: d.pageMargins,
    info: d.info,
    content: d.content ?? null,
    defaultStyle: d.defaultStyle,
    header: d.header(),
    footer: d.footer(2, 5),
    hasBackground: typeof d.background === 'function',
    background: d.background ? d.background(1, { width: 612, height: 792 }) : null,
  };
}

describe('pdf.ts golden parity (legacy js/lib/pdf.js oracle)', () => {
  const constants: Record<string, unknown> = { CONTENT_W, CHURCH, CHURCH_ADDRESS };
  itGolden('constants', constVectors as GoldenVector<string, unknown>[], (name) => constants[name]);

  itGolden(
    'sectionHeading',
    shVectors as unknown as GoldenVector<[unknown, string?, number?], unknown>[],
    (args) => sectionHeading(...args),
  );

  itGolden('th', thVectors as unknown as GoldenVector<[unknown, boolean?], unknown>[], (args) =>
    th(...args),
  );

  itGolden(
    'kpiBox',
    kpiVectors as unknown as GoldenVector<[unknown, string, string?, string?], unknown>[],
    (args) => probeKpi(kpiBox(...args)),
  );

  itGolden(
    'churchDocDef',
    docVectors as unknown as GoldenVector<ChurchDocDefOpts, unknown>[],
    (opts) => probeDocDef(churchDocDef(opts)),
  );
});
