// S07 golden parity for $lib/sanitize-html (port of js/lib/sanitize-html.js).
// The sanitizer allowlist is a security contract (D-005); this XSS corpus is
// the regression net. DOMParser ⇒ jsdom environment required (G-001).
//
// The fixture is DOM-dependent, so it is generated by the CAPTURE-gated test
// tests/unit/capture-sanitize-html.test.ts, which runs the LEGACY module:
//   CAPTURE=1 npx vitest run tests/unit/capture-sanitize-html.test.ts
// Until that fixture is committed, this suite reports one skipped test.
import { describe, it } from 'vitest';
import { itGolden, type GoldenVector } from '$lib/test/golden';
import { htmlIsEmpty, renderRichText, richToPlain, sanitizeHtml } from '$lib/sanitize-html';

type Fixture = {
  sanitizeHtml: GoldenVector<string | number | null, string>[];
  renderRichText: GoldenVector<string | null, string>[];
  richToPlain: GoldenVector<string | null, string>[];
  htmlIsEmpty: GoldenVector<string | null, boolean>[];
};

// Loaded dynamically (not a static import) so the suite still collects — as a
// single skipped test — before the fixture has been captured.
let fx: Fixture | null;
try {
  fx = (await import('../fixtures/sanitize-html.json')).default as unknown as Fixture;
} catch {
  fx = null;
}

if (fx) {
  const { sanitizeHtml: sv, renderRichText: rv, richToPlain: pv, htmlIsEmpty: ev } = fx;
  describe('sanitize-html golden (legacy js/lib/sanitize-html.js)', () => {
    itGolden('sanitizeHtml — XSS corpus', sv, (input) => sanitizeHtml(input as string));
    itGolden('renderRichText', rv, (input) => renderRichText(input));
    itGolden('richToPlain', pv, (input) => richToPlain(input));
    itGolden('htmlIsEmpty', ev, (input) => htmlIsEmpty(input));
  });
} else {
  describe('sanitize-html golden (legacy js/lib/sanitize-html.js)', () => {
    it.skip('fixture missing — run: CAPTURE=1 npx vitest run tests/unit/capture-sanitize-html.test.ts', () => {
      /* capture the legacy golden first (D-012) */
    });
  });
}
