// S07 golden parity for $lib/validators (port of js/lib/validators.js).
// Fixtures were generated by RUNNING THE LEGACY MODULE — never from the port
// (D-012). isValidEmail/isValidName take no non-string vectors: legacy throws
// on truthy non-strings, and the port's types forbid them.
import { describe } from 'vitest';
import { itGolden, type GoldenVector } from '$lib/test/golden';
import {
  formatUSPhoneNational,
  isValidEmail,
  isValidName,
  isValidUSPhone,
  normalizeUSPhone,
} from '$lib/validators';
import fixtureJson from '../fixtures/validators.json';

type Fixture = {
  isValidEmail: GoldenVector<string | null, boolean>[];
  normalizeUSPhone: GoldenVector<string | number | null, string | null>[];
  isValidUSPhone: GoldenVector<string | number | null, boolean>[];
  isValidName: GoldenVector<string | null, boolean>[];
  formatUSPhoneNational: GoldenVector<string | null, string>[];
};

const fx = fixtureJson as unknown as Fixture;

describe('validators golden (legacy js/lib/validators.js)', () => {
  itGolden('isValidEmail', fx.isValidEmail, (input) => isValidEmail(input));
  itGolden('normalizeUSPhone', fx.normalizeUSPhone, (input) => normalizeUSPhone(input));
  itGolden('isValidUSPhone', fx.isValidUSPhone, (input) => isValidUSPhone(input));
  itGolden('isValidName', fx.isValidName, (input) => isValidName(input));
  itGolden('formatUSPhoneNational', fx.formatUSPhoneNational, (input) =>
    formatUSPhoneNational(input),
  );
});
